<a href="https://colab.research.google.com/github/salahzaame/deep_learning_materials/blob/main/TF_course_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print (tf.__version__)

2.15.0


In [ ]:
## let's start by creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#let's check the dimension of a tensor using ndim (number of dimensions)
scalar.ndim

0

In [ ]:
#Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,4.],
                                [5.,6.],
                                [12.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 5.,  6.],
       [12.,  3.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let's create a tensor :
tensor = tf.constant([[[1,3,4],[1,1,3]],
                      [[3,1,4],[1,4,2]],
                      [[23,1,2],[1,12,1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  3,  4],
        [ 1,  1,  3]],

       [[ 3,  1,  4],
        [ 1,  4,  2]],

       [[23,  1,  2],
        [ 1, 12,  1]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### creating tensors with `tf.variable`

In [ ]:
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# let's try to change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)   # we can change an element of this tensor
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(2)  # we can't change an element of a tensor created with tf.constant()
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [ ]:
# we can use this to initialise the weights in our neural network.
random1 = tf.random.Generator.from_seed(1)  # setting seed for reproducebility
random1 = random1.normal(shape=(3,2))

random2 = tf.random.Generator.from_seed(1)
random2 = random2.normal(shape=(3,2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### let's shuffle the order of elements in a tensor :
it's better for when you don't want the inherent order to effect learning


In [ ]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)  # global level random seed
shuffled1 = tf.random.shuffle(not_shuffled)
shuffled2 = tf.random.shuffle(not_shuffled)
shuffled1, shuffled2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 2,  5],
        [10,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [10,  7],
        [ 3,  4]], dtype=int32)>)

If the global seed is set but the operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run of the program

> if we want our shuffled tensor to be in the same order we should use a global random seed

### ⏰ Other ways to build tensors

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

> tensors will run faster with GPUs

In [ ]:
import numpy as np
array = np.arange(1,25, dtype=np.int32)
tensor = tf.constant(array)
tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(array , shape = (2 , 3, 4))   # this is a tensor
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting infos from tensors

* shape
* Rank
* dimension
* size

In [ ]:
# let's make a rank 4 tensor
tensor_4 = tf.zeros(shape=(2,3,4,5))
tensor_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_4[0][2]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tensor_4.ndim, tensor_4.shape, tf.size(tensor_4)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors
tensors can be indexed like Python lists

In [ ]:
# Get the first 2 elements of each dimension
tensor_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index expect for the final one
tensor_4[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# rank 2 tensor
tensor_2 = tf.constant([[10,7],[3,4]])
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# get the last item of each row in our rank 2 tensor :
tensor_2[:  ,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimensions to our rank 2  tensor
rank_3_tensor = tensor_2[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(tensor_2, axis=-1)  # -1 for the end  and 0 for the start

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## ⛹ Manipulating tensors