<a href="https://colab.research.google.com/github/salahzaame/deep_learning_materials/blob/main/TF_course_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print (tf.__version__)

2.15.0


In [4]:
## let's start by creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#let's check the dimension of a tensor using ndim (number of dimensions)
scalar.ndim

0

In [6]:
#Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
#creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [12]:
#create another matrix
another_matrix = tf.constant([[10.,4.],
                                [5.,6.],
                                [12.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 5.,  6.],
       [12.,  3.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [17]:
#let's create a tensor :
tensor = tf.constant([[[1,3,4],[1,1,3]],
                      [[3,1,4],[1,4,2]],
                      [[23,1,2],[1,12,1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  3,  4],
        [ 1,  1,  3]],

       [[ 3,  1,  4],
        [ 1,  4,  2]],

       [[23,  1,  2],
        [ 1, 12,  1]]], dtype=int32)>

In [18]:
tensor.ndim

3

### creating tensors with `tf.variable`

In [22]:
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
# let's try to change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)   # we can change an element of this tensor
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [26]:
unchangeable_tensor[0].assign(2)  # we can't change an element of a tensor created with tf.constant()
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'